name: lefthook
description: Runs Lefthook pre-commit hooks
inputs:
  token:
    description: GitHub token to use for authentication
    required: true

runs:
  using: composite
  steps:
    - name: Checkout PR branch
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up pixi
      uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
      with:
        run-install: false

    - run: |
        mkdir lefthook
        cp $GITHUB_ACTION_PATH/lefthook.yaml ./lefthook.yaml
        cp $GITHUB_ACTION_PATH/pixi.toml ./lefthook/pixi.toml
        cp $GITHUB_ACTION_PATH/pixi.lock ./lefthook/pixi.lock
      shell: bash

    - name: lefthook
      run: pixi run --manifest-path ./lefthook/pixi.toml lefthook-run
      shell: bash

    - if: ${{!cancelled()}}
      run: |
        if ! git diff --quiet || ! git diff --cached --quiet; then
          echo "❌ Lefthook modified files. Please run lefthook locally and commit the fixes."
          git --no-pager diff
          exit 1
        fi
      shell: bash

    - name: Auto commit fixes
      if: ${{ github.event_name == 'workflow_call' && !cancelled() }}
      run: |
        rm ./lefthook.yaml
        rm -rf ./lefthook

        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add -A
        COMMENT_BODY=""

        if ! git diff --cached --quiet; then
          if git commit -m "apply lefthook fixes"; then
            if git push; then
              COMMENT_BODY="**Lefthook finished**
        ✅ Fixes applied and pushed successfully."
            else
              COMMENT_BODY="**Lefthook finished**
        ⚠️ Fixes committed locally, but **push failed**."
            fi
          else
            COMMENT_BODY="**Lefthook finished**
        ❌ Failed to commit fixes."
          fi
        else
          COMMENT_BODY="**Lefthook finished**
        ✅️ No changes were required."
        fi

        # Always attempt to comment
        gh pr comment "${{ github.event.pull_request.number }}" --edit-last --body "${COMMENT_BODY}" || echo "Failed to comment on PR"
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
