group:
  - files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
    repos: |
      Glatzel/clerk
      Glatzel/demon-forge
      Glatzel/pyxis
      Glatzel/fornax

  # rustfmt.toml
  - files:
    - source: ./rust/rustfmt.toml
      dest: ./rust/rustfmt.toml
    repos: |
      Glatzel/clerk

  - files:
      - source: ./rust/rustfmt.toml
        dest: ./rustfmt.toml
    repos: |
      Glatzel/fornax
      Glatzel/pyxis

  # cliff.toml
  - files:
    - source: ./common/cliff.toml
      dest: ./cliff.toml
    repos: |
      Glatzel/clerk
      Glatzel/pyxis
      Glatzel/fornax

