group:
  - repos: |
      Glatzel/cetus
      Glatzel/blocke
      Glatzel/demon-forge
      Glatzel/dxf2kml
      Glatzel/fornax
      Glatzel/hippo
      Glatzel/mason
      Glatzel/pyxis
      Glatzel/toolbox
      Glatzel/vinaya
    files:
      - source: ./.ci
        dest: ./.ci
        deleteOrphaned: true
      - source: ./.github/actions
        dest: ./.github/actions
        deleteOrphaned: true
      - source: ./.github/workflows/changelog.yml
        dest: ./.github/workflows/changelog.yml
      - source: ./.github/workflows/ci-lefthook.yml
        dest: ./.github/workflows/ci-lefthook.yml
      - source: ./.github/workflows/release.yml
        dest: ./.github/workflows/release.yml
      - source: ./common
        dest: ./

  - repos: Glatzel/blocke
    files:
      - source: ./rust/
        dest: ./esp32-c3
      - source: ./rust/
        dest: ./driver

  - repos: Glatzel/config-linux
    files:
      - source: ./common/tombi.toml
        dest: ./common/tombi.toml

  - repos: Glatzel/config-win
    files:
      - source: ./common/tombi.toml
        dest: ./common/tombi.toml

  - repos: Glatzel/demon-forge
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml

  - repos: Glatzel/dxf2kml
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml

  - repos: Glatzel/fornax
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml

      - source: ./rust
        dest: ./

  - repos: Glatzel/hippo
    files:
      - source: ./dotnet/
        dest: ./src

  - repos: Glatzel/mason
    files:
      - source: ./dotnet/
        dest: ./

  - repos: Glatzel/pyxis
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml

      - source: ./rust
        dest: ./python
      - source: ./rust
        dest: ./rust
      - source: ./rust
        dest: ./tools/gnss-receiver
      - source: ./rust
        dest: ./tools/pyxis-cli

  - repos: Glatzel/toolbox
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml

      - source: ./rust
        dest: ./rust
      - source: ./rust
        dest: ./tools/orc
      - source: ./rust
        dest: ./tools/ttyw
      - source: ./rust
        dest: ./tools/vinaya

  - repos: Glatzel/vinaya
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml

      - source: ./rust
        dest: ./native/rust

      - source: ./clang
        dest: ./
