group:
  - files:
      - source: python/static/
        dest: ./
    repos: |
      Glatzel/hippo
      Glatzel/ms-redeem
      Glatzel/py-bench
      Glatzel/py-glatzel
      Glatzel/vinaya
      Glatzel/watch-media
  - files:
      - source: dotnet/static/
        dest: ./
    repos: |
      Glatzel/mason
      Glatzel/cs-glatzel
