group:
  - repos: Glatzel/cetus
    files:
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml

  - repos: Glatzel/clerk
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./rust/rustfmt.toml
        dest: ./rust/rustfmt.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml
      - source: ./rust/scripts/cargo-clippy.ps1
        dest: ./rust/scripts/cargo-clippy.ps1

  - repos: Glatzel/demon-forge
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml

  - repos: Glatzel/fornax
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./rust/rustfmt.toml
        dest: ./rustfmt.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml
      - source: ./rust/scripts/cargo-clippy.ps1
        dest: ./scripts/cargo-clippy.ps1

  - repos: Glatzel/pyxis
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./rust/rustfmt.toml
        dest: ./rustfmt.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml
      - source: ./rust/scripts/cargo-clippy.ps1
        dest: ./rust/scripts/cargo-clippy.ps1
      - source: ./rust/scripts/cargo-clippy.ps1
        dest: ./rust-cuda/scripts/cargo-clippy.ps1
      - source: ./rust/scripts/cargo-clippy.ps1
        dest: ./python/scripts/cargo-clippy.ps1
