group:
  - repos: Glatzel/blocke
    files:

      - source: ./lefthook/
        dest: ./lefthook/
      - source: ./lefthook.yaml
        dest: ./lefthook.yaml
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./rust/rustfmt.toml
        dest: ./rustfmt.toml

      - source: ./rust/scripts/
        dest: ./esp32-c3/scripts/

  - repos: Glatzel/cetus
    files:
      - source: ./lefthook/
        dest: ./lefthook/
      - source: ./lefthook.yaml
        dest: ./lefthook.yaml
      - source: ./common/taplo.toml
        dest: ./taplo.toml

  - repos: Glatzel/toolbox
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./lefthook/
        dest: ./lefthook/
      - source: ./lefthook.yaml
        dest: ./lefthook.yaml
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml
      - source: ./rust
        dest: ./rust

  - repos: Glatzel/demon-forge
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./lefthook/
        dest: ./lefthook/
      - source: ./lefthook.yaml
        dest: ./lefthook.yaml
      - source: ./common/taplo.toml
        dest: ./taplo.toml

  - repos: Glatzel/fornax
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./lefthook/
        dest: ./lefthook/
      - source: ./lefthook.yaml
        dest: ./lefthook.yaml
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml
      - source: ./rust/scripts/cargo-clippy.ps1
        dest: ./scripts/cargo-clippy.ps1
      - source: ./rust
        dest: ./

  - repos: Glatzel/pyxis
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./lefthook/
        dest: ./lefthook/
      - source: ./lefthook.yaml
        dest: ./lefthook.yaml
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml

      - source: ./rust
        dest: ./python
      - source: ./rust
        dest: ./rust
      - source: ./rust
        dest: ./rust-cuda
