
group:
  - files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
    repos: |
      Glatzel/clerk
      Glatzel/demon-forge
      Glatzel/pyxis
      Glatzel/fornax

  - files:
      - source: ./common/taplo.toml
        dest: ./taplo.toml
    repos: |
      Glatzel/clerk
      Glatzel/demon-forge
      Glatzel/pyxis
      Glatzel/fornax

  - files:
    - source: ./rust/rustfmt.toml
      dest: ./rust/rustfmt.toml
    repos: |
      Glatzel/clerk
      Glatzel/pyxis

  - files:
    - source: ./rust/rustfmt.toml
      dest: ./rustfmt.toml
    repos: |
      Glatzel/fornax

  - files:
    - source: ./pre-commit/
      dest: ./pre-commit/
    repos: |
      Glatzel/fornax