group:
  - repos: Glatzel/cetus
    files:
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml

  - repos: Glatzel/blocke
    files:
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./rust
        dest: ./
      - source: ./common/cliff.toml
        dest: ./cliff.toml

  - repos: Glatzel/toolbox
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml
      - source: ./rust
        dest: ./rust

  - repos: Glatzel/demon-forge
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml

  - repos: Glatzel/fornax
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml
      - source: ./rust/scripts/cargo-clippy.ps1
        dest: ./scripts/cargo-clippy.ps1
      - source: ./rust
        dest: ./

  - repos: Glatzel/pyxis
    files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
      - source: ./common/cliff.toml
        dest: ./cliff.toml

      - source: ./rust
        dest: ./python
      - source: ./rust
        dest: ./rust
      - source: ./rust
        dest: ./rust-cuda
