group:
  - files:
      - source: ./python/ruff.toml
        dest: ./ruff.toml
      - source: ./pre-commit/
        dest: ./pre-commit/
      - source: ./common/taplo.toml
        dest: ./taplo.toml
    repos: |
      Glatzel/clerk
      Glatzel/demon-forge
      Glatzel/pyxis
      Glatzel/fornax

  - files:
      - source: ./rust/rustfmt.toml
        dest: ./rust/rustfmt.toml
    repos: |
      Glatzel/clerk

  - files:
      - source: ./rust/rustfmt.toml
        dest: ./rustfmt.toml
    repos: |
      Glatzel/fornax
      Glatzel/pyxis

# cliff
Glatzel/clerk:
  - source: ./common/cliff.toml
    dest: ./cliff.toml
    template:
      repo: "clerk"
Glatzel/pyxis:
  - source: ./common/cliff.toml
    dest: ./cliff.toml
    template:
      repo: "pyxis"
Glatzel/fornax:
  - source: ./common/cliff.toml
    dest: ./cliff.toml
    template:
      repo: "fornax"
