# region python
- id: ruff-lint
  name: Ruff lint
  entry: pixi run --manifest-path ./pre-commit/pixi.toml hook-ruff-lint
  language: system
  types_or: [python, pyi]
  require_serial: true
  stages: [pre-commit, manual]

- id: ruff-format
  name: Ruff format
  entry: pixi run --manifest-path ./pre-commit/pixi.toml hook-ruff-format
  language: system
  types_or: [python, pyi]
  require_serial: true
  stages: [pre-commit, manual]

- id: numpydoc
  name: numpydoc
  entry: pixi run --manifest-path ./pre-commit/pixi.toml hook-numpydoc
  language: system
  types_or: [python]
  stages: [pre-commit, manual]

# region misc
- id: taplo
  name: TOML format
  entry: pixi run --manifest-path ./pre-commit/pixi.toml hook-taplo
  language: system
  types: [file, toml]
  stages: [pre-commit, manual]

- id: actionlint
  name: Lint GitHub Actions workflow files
  language: system
  entry: pixi run --manifest-path ./pre-commit/pixi.toml actionlint
  types: [yaml]
  files: ^\.github/workflows/
  stages: [pre-commit, manual]

- id: typos
  name: typos
  entry: pixi run --manifest-path ./pre-commit/pixi.toml hook-typos
  language: system
  types: [text]
  stages: [pre-commit, manual]

- id: markdown
  name: markdown
  entry: pixi run --manifest-path ./pre-commit/pixi.toml hook-markdown
  language: system
  types: [markdown]
  stages: [pre-commit, manual]
