# TOML format
- id: taplo-format
  name: TOML format
  entry: pixi run --manifest-path ./pre-commit/pixi.toml toml-format
  language: system
  types: [file, toml]
  stages: [pre-commit, manual]

#rust
- id: cargo-clippy
  name: cargo-clippy
  entry: pwsh -NoProfile -Command "$ErrorActionPreference ='Stop';$PSNativeCommandUseErrorActionPreference = $true;foreach ($f in $args) { &$f}"
  language: rust
  files: ".*/cargo-clippy.ps1"
  require_serial: true
  stages: [pre-commit, manual]

- id: cargo-fmt
  name: cargo-fmt
  entry: pwsh -NoProfile -Command "$ErrorActionPreference ='Stop';$PSNativeCommandUseErrorActionPreference = $true;foreach ($f in $args) { &$f}"
  language: rust
  language_version: nightly
  files: ".*/cargo-fmt.ps1"
  require_serial: true
  stages: [pre-commit, manual]
