[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
pre-commit-run = "pre-commit run --all-files"

hook-csharpier = "cd ..; bash -c 'numpydoc lint \"$@\" --ignore ES01 EX01 GL08 PR04 RT03 SA01 SA04' -- "
hook-numpydoc = "cd ..; bash -c 'numpydoc lint \"$@\" --ignore ES01 EX01 GL08 PR04 RT03 SA01 SA04' -- "
hook-ruff-lint = "cd ..;ruff check --fix --show-fixes --exit-non-zero-on-fix --force-exclude;"
hook-ruff-format = "cd ..;ruff format --force-exclude --exit-non-zero-on-format"
hook-taplo = { cmd = "taplo fmt", env = { RUST_LOG = "warn" } }

[dependencies]
actionlint = "==1.7.7"
numpydoc = "==1.8.0"
pre-commit = "==4.2.0"
pre-commit-hooks = "==5.0.0"
python = "3.11.*"
ruff = "==0.11.8"
taplo = "==0.9.3"
