[project]
channels = ["conda-forge"]
platforms = ["linux-64","win-64"]

[tasks]
run-check = "pwsh -f run-check.ps1"
pre-commit-run = "pre-commit run --all-files"
toml-format = { cmd = "taplo fmt", env = { RUST_LOG = "warn" } }
ruff-check="ruff --fix --show-fixes --exit-non-zero-on-fix"
[dependencies]
actionlint = "==1.7.4"
numpydoc = "==1.8.0"
pre-commit = "==4.2.0"
pre-commit-hooks = "==4.6.0"
python = "3.11.*"
ruff = "==0.11.7"
taplo = "==0.9.1"
