[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
pre-commit-run = "pre-commit run --all-files"
toml-format = { cmd = "taplo fmt", env = { RUST_LOG = "warn" } }

[dependencies]
actionlint = "==1.7.4"
pre-commit = "==4.2.0"
pre-commit-hooks = "==4.6.0"
ruff = "==0.11.7"
taplo = "==0.9.1"
