[workspace]
authors = ["Glatzel"]
channels = ["conda-forge"]
name = "pre-commit"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
pre-commit-run = "pre-commit run --all-files"

[dependencies]
pre-commit = "*"
pre-commit-hooks = "*"