[workspace]
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]

[package]

[dependencies]

[profile.dist]
codegen-units = 1
debug = false
inherits = "release"
lto = "fat"
opt-level = 3
strip = true
