name: post-release

on:
  workflow_call:

concurrency:
  group: changelog-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          run-install: false

      - run: pixi global install git-cliff > changelog.md

      - run: git-cliff

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update changelog.md"
          title: "chore: update changelog.md"
          branch: update-changelog
          base: main
          delete-branch: true
          add-paths: changelog.md
          assignees: Glatzel
          draft: false