name: update-changelog

on:
  workflow_call:

concurrency:
  group: changelog-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          run-install: false

      - run: pixi global install git-cliff

      - run: git-cliff > CHANGELOG.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update changelog.md"
          title: "chore: update changelog.md"
          branch: update-changelog
          base: main
          delete-branch: true
          add-paths: CHANGELOG.md
          assignees: Glatzel
          draft: false
