# This File is automatically synchronized from https://github.com/Glatzel/template

name: lefthook
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            ./lefthook/.pixi
          key: lefthook-${{ hashFiles('lefthook.yaml','./lefthook/*.*')}}
          restore-keys: |
            lefthook

      #  pixi setup
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@main
        with:
          run-install: false

      # rust setup
      - uses: Swatinem/rust-cache@v2

      # pre-commit
      - name: lefthook
        run: pixi run --manifest-path ./lefthook/pixi.toml lefthook-run
        shell: pwsh

      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
