name: ci

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lefthook:
    uses: ./.github/workflows/ci-lefthook.yml
    permissions:
      contents: write
      pull-requests: write

  python:
    strategy:
      fail-fast: false
      matrix:
        include:
          - pixi-environment: dev
            args: ./tests
          - args: ./tests --color=yes
          - foo: ""
    runs-on: ubuntu-slim
    steps:
      - parallel:
          - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
          - name: Set up pixi
            uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
            with:
              run-install: false
      - uses: ./.github/actions/python/pytest
        with:
          working-directory: test/python

  rust:
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: ubuntu-slim

          - machine: ubuntu-slim
            toolchain: stable
            components: clippy
            targets: x86_64-unknown-linux-gnu
            build-options: --release

          - machine: ubuntu-latest
            toolchain: stable
            components: "rustfmt clippy"
            targets: x86_64-unknown-linux-gnu
            build-options: --all-features

          - machine: ubuntu-latest
            toolchain: nightly
            components: "rustfmt clippy"
            targets: aarch64-unknown-linux-gnu
            build-options: --release

    runs-on: ${{ matrix.machine }}
    steps:
      - parallel:
          - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
          - name: Set up pixi
            uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
            with:
              run-install: false
      - uses: ./.github/actions/rust/setup-rust
        with:
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
          targets: ${{ matrix.targets }}
      - uses: ./.github/actions/rust/cargo-build
        with:
          options: ${{ matrix.build-options }}
          working-directory: test/rust
      - uses: ./.github/actions/rust/cargo-clippy
        with:
          working-directory: test/rust
      - uses: ./.github/actions/rust/cargo-doc
        with:
          working-directory: test/rust
      - uses: ./.github/actions/rust/cargo-test
        with:
          working-directory: test/rust
