name: pre-commit
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "*.md"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: pre-commit-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ./pre-commit/.pixi
            ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml','./pre-commit/*')}}
          restore-keys: |
            pre-commit
      #  pixi setup
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@main
        with:
          run-install: false
      - run: pixi install --manifest-path ./pre-commit/pixi.toml
        shell: pwsh

      # rust setup
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2

      # pre-commit
      - name: pre-commit
        run: |
          pixi run --manifest-path ./pre-commit/pixi.toml pre-commit autoupdate
          pixi run --manifest-path ./pre-commit/pixi.toml pre-commit --color=always --show-diff-on-failure
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
