name: pre-commit
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "*.md"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: pre-commit-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #  pixi setup
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@main
        with:
          run-install: false
      - run: pixi install --manifest-path ./pre-commit/pixi.toml
      - run: |
          New-Item ./pre-commit -ItemType Directory -ErrorAction SilentlyContinue
          aria2c -c -x16 -s16 -d ./pre-commit "https://raw.githubusercontent.com/Glatzel/template/main/pre-commit/pixi.toml"
        shell: pwsh
      - uses: actions/cache@v4
        with:
          path: |
            ./pre-commit/.pixi
            ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml','./pre-commit/*')}}
          restore-keys:
            pre-commit-
      # rust setup
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
