name: pre-commit
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "*.md"
  workflow_call:

concurrency:
  group: pre-commit-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v4

      - if: ${{github.repository != 'Glatzel/template'}}
        run: |
          New-Item ./pre-commit -ItemType Directory -ErrorAction SilentlyContinue
          curl -L -o .pre-commit-config.yaml  https://raw.githubusercontent.com/Glatzel/template/main//.pre-commit-config.yaml
          curl -L -o ./pre-commit/pixi.toml  https://raw.githubusercontent.com/Glatzel/template/main//pre-commit/pixi.toml
          curl -L -o ./pre-commit/run-check.ps1  https://raw.githubusercontent.com/Glatzel/template/main//pre-commit/run-check.ps1
        shell: pwsh

      - uses: actions/cache@v4
        with:
          path: ./pre-commit/.pixi
          key: pre-commit-${{ hashFiles('./pre-commit/*','.pre-commit-config.yaml')}}

      
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@main
        with:
          run-install: false

      - run: |
          pixi config set --global shell.change-ps1 false
          pixi install --manifest-path ./pre-commit/pixi.toml

      - name: pre-commit
        run: pixi run --manifest-path ./pre-commit/pixi.toml pre-commit-run --color=always --show-diff-on-failure

      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
