name: pre-commit
on:
    workflow_call:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          New-Item ./pre-commit -ItemType Directory
          curl -L -o .pre-commit-config.yaml  https://raw.githubusercontent.com/Glatzel/template/main//.pre-commit-config.yaml
          curl -L -o ./pre-commit/pixi.toml  https://raw.githubusercontent.com/Glatzel/template/main//pre-commit/pixi.toml
        shell: pwsh

      - uses: actions/cache@v4
        with:
          path: ./pre-commit/.pixi
          key: pre-commit-${{ hashFiles('./pre-commit/pixi.toml')}}

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@main
        with:
          run-install: false

      - name: pre-commit
        run: pixi run --manifest-path ./pre-commit/pixi.toml pre-commit-run --color=always --show-diff-on-failure