name: ruff-lint
on:
  workflow_call:

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.4
        with:
          run-install: false

      - name: install ruff
        run: pixi global install ruff

      - name: lint
        run: ruff check --output-format=github .
